### ISSUE TITLE
User or bot?

### ISSUE THREAD

**Issue by giiovi** [therealOri/ChatterEye#3]
is this for a Discord User account or is this for a Discord Application?

**Comment by therealOri** [comment]
Discord application/bot.

**Comment by giiovi** [comment]
But it wont work 
i installed toml
Traceback (most recent call last):
  File "C:\Users\Megaport\Documents\OpenEye\Chatter\eye.py", line 5, in <module>
    import tomllib
ModuleNotFoundError: No module named 'tomllib'

**Comment by therealOri** [comment]
Can you let me know what version of python you're using?

Also, tomllib should be part of the python standard library and should not need to be installed.

**Comment by therealOri** [comment]
Well, if you need any more help with your issue, feel free to let me know and I'll see if I can help.

For now, this issue will be closed as stale or inactive.
